__version__ = "1.1.2"
__author__ = "Palo Alto Cortex Xpanse"
__license__ = "ISC"
__maintainer__ = "Palo Alto Cortex Xpanse"
__email__ = "xpanse-integrations@paloaltonetworks.com"
__status__ = "Production"
