__version__ = "2.1.0-rc1"
__author__ = "Palo Alto Cortex Xpanse"
__license__ = "ISC"
__maintainer__ = "Palo Alto Cortex Xpanse"
__email__ = "xpanse-integrations@paloaltonetworks.com"
__status__ = "Production"
