name: Python Package Release and Publish

on:
  push:
    branches:
      - main
      - Development
    tags:
      - 'v*.*.*'

jobs:
  build-n-publish:
    name: Create Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        release-version: [2.1.0]
    steps:
      - uses: actions/checkout@v1
      - name: Get tag version
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install setuptools wheel twine
          python -m pip install --upgrade twine
          python -m pip install --upgrade build
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ matrix.release-version }}
          release_name: Release ${{ matrix.release-version}}
          body: |
            Changes in this Release
            - Minor updates to project description
          draft: false
          prerelease: false
      - name: Build distribution
        run: |
         python setup.py sdist bdist_wheel
      - name: Publish Package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload --repository pypi dist/*